// import { SwitchThemeProvider } from "./components/switchTheme";
import "./globals.css";

export const metadata = {
  title: "Resume",
  description: "Generated by Mahmoud Khalil",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <SwitchThemeProvider>
    <html lang="en">
      <body>{children}</body>
    </html>
    // </SwitchThemeProvider>
  );
}
